-- MySQL Script generated by MySQL Workbench
-- Tue May  3 12:52:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crunchyroll_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crunchyroll_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crunchyroll_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crunchyroll_database` ;

-- -----------------------------------------------------
-- Table `crunchyroll_database`.`animeshow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`animeshow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `overview` VARCHAR(45) NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  `actor` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`season` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `animeshow_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_season_animeshow1_idx` (`animeshow_id` ASC) VISIBLE,
  CONSTRAINT `fk_season_animeshow1`
    FOREIGN KEY (`animeshow_id`)
    REFERENCES `crunchyroll_database`.`animeshow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`episode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `season_id` INT NOT NULL,
  PRIMARY KEY (`id`, `season_id`),
  INDEX `fk_episode_season1_idx` (`season_id` ASC) VISIBLE,
  CONSTRAINT `fk_episode_season1`
    FOREIGN KEY (`season_id`)
    REFERENCES `crunchyroll_database`.`season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart` INT NOT NULL,
  `price` INT NOT NULL,
  `review` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `product_id` INT NOT NULL,
  `animeshow_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`, `animeshow_id`),
  INDEX `fk_user_animeshow1_idx` (`animeshow_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `crunchyroll_database`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_animeshow1`
    FOREIGN KEY (`animeshow_id`)
    REFERENCES `crunchyroll_database`.`animeshow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rule` VARCHAR(45) NOT NULL,
  `feedback` VARCHAR(45) NOT NULL,
  `goal` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_game_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crunchyroll_database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicationDate` DATE NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_news_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crunchyroll_database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`manga_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`manga_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crunchyroll_database`.`manga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crunchyroll_database`.`manga` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `mangacategory_id` INT NOT NULL,
  PRIMARY KEY (`id`, `news_id`, `news_user_id`),
  INDEX `fk_manga_news1_idx` (`news_id` ASC, `news_user_id` ASC) VISIBLE,
  INDEX `fk_manga_mangacategory1_idx` (`mangacategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_manga_news1`
    FOREIGN KEY (`news_id` , `news_user_id`)
    REFERENCES `crunchyroll_database`.`news` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manga_mangacategory1`
    FOREIGN KEY (`mangacategory_id`)
    REFERENCES `crunchyroll_database`.`mangacategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
